-- subscriptions table
CREATE TABLE IF NOT EXISTS tb_subscriptions (
   instrument_id VARCHAR(32) PRIMARY KEY,
   product_id VARCHAR(16),
   product_class CHAR(1),
   exchange_id VARCHAR(16),
   sort_order INT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);   


-- Instruments Table
CREATE TABLE IF NOT EXISTS tb_instruments (
    instrument_id VARCHAR(32) PRIMARY KEY,
    instrument_name VARCHAR(64), -- Added
    exchange_id VARCHAR(16),
    -- 增加品种ID，方便做品种级别的配置查询
    product_id VARCHAR(16), 
    product_class CHAR(1),
    volume_multiple INT,
    price_tick DOUBLE PRECISION,
    max_market_order_volume INT,
    min_market_order_volume INT,
    max_limit_order_volume INT,
    min_limit_order_volume INT,
    create_date DATE,
    open_date DATE,
    expire_date DATE,
    start_deliver_date DATE,
    end_deliver_date DATE,
    is_trading BOOLEAN,
    
    -- 建议增加：底层标的，做期权时非常重要
    underlying_instr_id VARCHAR(32), 
    -- 建议增加：执行价，如果是期权的话
    strike_price DOUBLE PRECISION,

    -- Margin Ratios
    long_margin_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    long_margin_ratio_by_volume DOUBLE PRECISION DEFAULT 0,
    short_margin_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    short_margin_ratio_by_volume DOUBLE PRECISION DEFAULT 0,

    -- Commission Ratios
    open_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    open_ratio_by_volume DOUBLE PRECISION DEFAULT 0,
    close_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    close_ratio_by_volume DOUBLE PRECISION DEFAULT 0,
    close_today_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    close_today_ratio_by_volume DOUBLE PRECISION DEFAULT 0,

    -- 记录最后一次更新时间，便于排查数据是否陈旧
    last_update_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Orders Table
CREATE TABLE IF NOT EXISTS tb_orders (
    order_ref VARCHAR(13), -- unique ref generated by API
    request_id INT,
    front_id INT,
    session_id INT,
    exchange_id VARCHAR(16),
    instrument_id VARCHAR(32),
    direction CHAR(1), -- '0' Buy, '1' Sell
    offset_flag CHAR(1), -- '0' Open, '1' Close, '3' CloseToday
    limit_price DOUBLE PRECISION,
    volume_total_original INT,
    volume_traded INT,
    volume_total INT, -- remaining
    order_status CHAR(1), -- 'a' Unknown, '0' AllTraded, '5' Canceled...
    status_msg VARCHAR(256),
    strategy_id VARCHAR(32), -- 策略ID，用于区分不同策略的单子
    user_id VARCHAR(16),
    broker_id VARCHAR(16),
    insert_date VARCHAR(9),
    insert_time VARCHAR(9),
    active_time VARCHAR(9),
    cancel_time VARCHAR(9),
    sequence_no INT,
    
    -- Composite primary key or just a unique ID
    -- OrderRef resets every session? Using FrontID+SessionID+OrderRef is safest
    id SERIAL PRIMARY KEY,
    CONSTRAINT uniq_order UNIQUE (front_id, session_id, order_ref)
);

-- Trades Table
CREATE TABLE IF NOT EXISTS tb_trades (
    trade_id VARCHAR(21),
    order_ref VARCHAR(13), -- Ref to Order
    exchange_id VARCHAR(16),
    instrument_id VARCHAR(32),
    direction CHAR(1),
    offset_flag CHAR(1),
    price DOUBLE PRECISION,
    volume INT,
    trade_date VARCHAR(9),
    trade_time VARCHAR(9),
    trade_type CHAR(1),
    price_source CHAR(1),
    strategy_id VARCHAR(32), -- 策略ID
    user_id VARCHAR(16),
    broker_id VARCHAR(16),
    
    id SERIAL PRIMARY KEY,
    CONSTRAINT uniq_trade UNIQUE (exchange_id, trade_id, direction) -- TradeID is unique within Exchange? Usually yes.
);

-- Strategies Table (策略配置表)
-- 设计思路：使用 JSONB 存储差异化的策略参数，满足网格、突破、条件单等多种需求
CREATE TABLE IF NOT EXISTS tb_strategies (
    strategy_id VARCHAR(32) PRIMARY KEY,
    strategy_name VARCHAR(64) NOT NULL,
    
    -- 策略类型: 'CONDITION'(条件单), 'GRID'(网格), 'BREAKOUT'(突破), 'CTA'(趋势)
    strategy_type VARCHAR(32) NOT NULL,
    
    -- 标的合约 (如果是跨品种套利，可存主合约或置空在 params 中指定)
    instrument_id VARCHAR(32),
    exchange_id VARCHAR(16),
    
    -- 核心参数区 (JSONB):
    -- 1. 条件单: { "trigger_price": 3600, "condition": ">=", "action": "Buy", "volume": 1 }
    -- 2. 网格: { "upper_price": 4000, "lower_price": 3500, "grid_step": 10, "vol_per_grid": 1 }
    -- 3. 突破: { "resistance_level": 3800, "support_level": 3400, "lookback_period": 20 }
    parameters JSONB, 
    
    -- 运行状态: 0=Stop(停止), 1=Running(运行), 2=Paused(暂停), 9=Error(异常)
    status INT DEFAULT 0,
    status_msg VARCHAR(256), -- 记录最后的状态信息或报错
    
    user_id VARCHAR(16),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 索引：方便按用户和类型查询
CREATE INDEX IF NOT EXISTS idx_strategy_user ON tb_strategies(user_id);
CREATE INDEX IF NOT EXISTS idx_strategy_type ON tb_strategies(strategy_type);


-- Condition Orders Table (云端条件单/预埋单表)
-- Aligning with DBManager.cpp implementation
CREATE TABLE IF NOT EXISTS tb_condition_orders (
    request_id BIGINT PRIMARY KEY,
    
    instrument_id VARCHAR(32),
    trigger_price DOUBLE PRECISION,
    compare_type INT, -- 0: >=, 1: <= (Matches CompareType enum)
    
    status INT, -- 0: Pending, 1: Triggered, 2: Canceled
    
    direction CHAR(1),
    offset_flag CHAR(1),
    volume INT,
    limit_price DOUBLE PRECISION,
    
    strategy_id VARCHAR(32),
    
    insert_time TIMESTAMP DEFAULT NOW()
);

-- CREATE INDEX IF NOT EXISTS idx_cond_status ON tb_condition_orders(status);
