-- subscriptions table
CREATE TABLE IF NOT EXISTS tb_subscriptions (
   instrument_id VARCHAR(32) PRIMARY KEY,
   product_id VARCHAR(16),
   product_class CHAR(1),
   exchange_id VARCHAR(16),
   sort_order INT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);   


-- Instruments Table
CREATE TABLE IF NOT EXISTS tb_instruments (
    instrument_id VARCHAR(32) PRIMARY KEY,
    instrument_name VARCHAR(64), -- Added
    exchange_id VARCHAR(16),
    -- 增加品种ID，方便做品种级别的配置查询
    product_id VARCHAR(16), 
    product_class CHAR(1),
    volume_multiple INT,
    price_tick DOUBLE PRECISION,
    max_market_order_volume INT,
    min_market_order_volume INT,
    max_limit_order_volume INT,
    min_limit_order_volume INT,
    create_date DATE,
    open_date DATE,
    expire_date DATE,
    start_deliver_date DATE,
    end_deliver_date DATE,
    is_trading BOOLEAN,
    
    -- 建议增加：底层标的，做期权时非常重要
    underlying_instr_id VARCHAR(32), 
    -- 建议增加：执行价，如果是期权的话
    strike_price DOUBLE PRECISION,

    -- Margin Ratios
    long_margin_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    long_margin_ratio_by_volume DOUBLE PRECISION DEFAULT 0,
    short_margin_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    short_margin_ratio_by_volume DOUBLE PRECISION DEFAULT 0,

    -- Commission Ratios
    open_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    open_ratio_by_volume DOUBLE PRECISION DEFAULT 0,
    close_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    close_ratio_by_volume DOUBLE PRECISION DEFAULT 0,
    close_today_ratio_by_money DOUBLE PRECISION DEFAULT 0,
    close_today_ratio_by_volume DOUBLE PRECISION DEFAULT 0,

    -- 记录最后一次更新时间，便于排查数据是否陈旧
    last_update_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Orders Table
CREATE TABLE IF NOT EXISTS tb_orders (
    order_ref VARCHAR(13), -- unique ref generated by API
    request_id INT,
    front_id INT,
    session_id INT,
    exchange_id VARCHAR(16),
    instrument_id VARCHAR(32),
    direction CHAR(1), -- '0' Buy, '1' Sell
    offset_flag CHAR(1), -- '0' Open, '1' Close, '3' CloseToday
    limit_price DOUBLE PRECISION,
    volume_total_original INT,
    volume_traded INT,
    volume_total INT, -- remaining
    order_status CHAR(1), -- 'a' Unknown, '0' AllTraded, '5' Canceled...
    status_msg VARCHAR(256),
    user_id VARCHAR(16),
    broker_id VARCHAR(16),
    insert_date VARCHAR(9),
    insert_time VARCHAR(9),
    active_time VARCHAR(9),
    cancel_time VARCHAR(9),
    sequence_no INT,
    
    -- Composite primary key or just a unique ID
    -- OrderRef resets every session? Using FrontID+SessionID+OrderRef is safest
    id SERIAL PRIMARY KEY,
    CONSTRAINT uniq_order UNIQUE (front_id, session_id, order_ref)
);

-- Trades Table
CREATE TABLE IF NOT EXISTS tb_trades (
    trade_id VARCHAR(21),
    order_ref VARCHAR(13), -- Ref to Order
    exchange_id VARCHAR(16),
    instrument_id VARCHAR(32),
    direction CHAR(1),
    offset_flag CHAR(1),
    price DOUBLE PRECISION,
    volume INT,
    trade_date VARCHAR(9),
    trade_time VARCHAR(9),
    trade_type CHAR(1),
    price_source CHAR(1),
    user_id VARCHAR(16),
    broker_id VARCHAR(16),
    
    id SERIAL PRIMARY KEY,
    CONSTRAINT uniq_trade UNIQUE (exchange_id, trade_id, direction) -- TradeID is unique within Exchange? Usually yes.
);
